#!/usr/bin/env node
// ✅ Curriculum Tracker Build Script v5.5.0
// Runs on Vercel during deployment
// Splits app.js into 3 chunks for parallel browser loading
// This ensures app-admin.js and app-features.js are GENERATED by the build,
// not uploaded manually - so they always exist in the deployment

const fs = require('fs');
const path = require('path');

console.log('📦 Build: Splitting app.js into chunks...');

const appJs = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const lines = appJs.split('\n');
const total = lines.length;

console.log(`   Source: app.js (${total} lines, ${(appJs.length/1024).toFixed(0)}KB)`);

// Split points (based on app.js v5.5.0 - function boundaries)
const ADMIN_START   = 12950; // function AdminView(
const FEATURES_START = 20433; // function AdminAttendanceAnalytics(

const chunk1 = lines.slice(0, ADMIN_START).join('\n');
const chunk2 = lines.slice(ADMIN_START, FEATURES_START).join('\n');
const chunk3 = lines.slice(FEATURES_START).join('\n');

// Write chunk 2: app-admin.js
const header2 = `// ✅ CHUNK 2: Admin + Attendance (auto-generated by build-split.js)\n`;
fs.writeFileSync(path.join(__dirname, 'app-admin.js'), header2 + chunk2);
console.log(`   ✅ app-admin.js: ${(chunk2.length/1024).toFixed(0)}KB`);

// Write chunk 3: app-features.js  
const header3 = `// ✅ CHUNK 3: Features (auto-generated by build-split.js)\n`;
fs.writeFileSync(path.join(__dirname, 'app-features.js'), header3 + chunk3);
console.log(`   ✅ app-features.js: ${(chunk3.length/1024).toFixed(0)}KB`);

// Overwrite app.js with chunk 1 only (app.js stays as chunk 1)
const header1 = `// ✅ CHUNK 1: Core (auto-generated by build-split.js)\n`;
fs.writeFileSync(path.join(__dirname, 'app.js'), header1 + chunk1);
console.log(`   ✅ app.js (chunk 1): ${(chunk1.length/1024).toFixed(0)}KB`);

console.log('✅ Build: Split complete! 3 chunks ready for parallel loading.');
console.log(`   Total: ${(appJs.length/1024).toFixed(0)}KB split into ${(chunk1.length/1024).toFixed(0)}KB + ${(chunk2.length/1024).toFixed(0)}KB + ${(chunk3.length/1024).toFixed(0)}KB`);
